### PR TITLE
Enabled boiloff with Modular Fuel Tanks

### PR DESCRIPTION
**Pull request by dlrk2**
Modified CryoTanksFuelTankSwitcher.cfg and CryoTanksProceduralFuelTanks.cfg to only block boil off when Real Fuels is used, not when modular fuel tanks is used

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
I thought I'd merged this last night, but I guess I didn't!

Will be in the next set of updates.

**Comment by ChrisAdderley** [comment]
Actually, looked at the changes. It looks like you're just re-enabling the tank switcher component for cases when MFT is installed. This might not be what you want - it will add the part switching and stuff modules. Instead look at CryoTanksModularFuels, you may just want to enable the boiloff (not the switchers)  in there?

**Comment by dlrk2** [comment]
Yeah, that would have been a better ideal! I'll switch it around and redo
the PR

**Comment by ChrisAdderley** [comment]
Good stuff. Also, please make sure to target the PR to `dev`, it saves some merge headaches.

**Pull request closed without merging**
